const Nightmare = require('nightmare')
const nightmare = Nightmare({
  show: true,
  waitTimeout: 600000
})

nightmare
  .goto('https://demoapp.sandbox.aggreg8.hu')
  .click('#share-account-button')
  .wait('#username')
  .type('#username', 'istvan.kadar.js@gmail.com')
  .type('#password', 'asdf1234')
  .click('#kc_input_button')
  .wait('.mat-select-arrow')
  .click('.mat-select-arrow')
  .click('#mat-option-7')
  .wait(2000)
  .click('.mat-raised-button')
  .wait('#username')
  .type('#mainAccountNumber', 1103420034278)
  .type('#username', 3535419)
  .type('#password', 'London12')
  .click('.bank-login-button') 
  .wait('#sync-done-icon') 
  .click('.bank-login-button') 
  .wait('#account-list') 
  .click('.mat-checkbox') 
  .wait(3000)
  .wait('#consentedAccounsBlock > div > div:nth-child(2) > div > button')
  .click('#consentedAccounsBlock > div > div:nth-child(2) > div > button') 
  .wait(3000)
  .wait('#flex > button.right.mediumDesktopBtn.mat-raised-button > span') 
  .click('#flex > button.right.mediumDesktopBtn.mat-raised-button > span')  
  .wait("table[class=striped]")
  .goto('https://ui.sandbox.aggreg8.hu')
  .wait(2000)
  .type('#username', 'istvan.kadar.js@gmail.com')
  .type('#password', 'asdf1234')
  .click('#kc_input_button')
  .wait(2000)
  .click('#mat-tab-content-0-0 > div > app-bank-access-consent-list-component > div > div.consent-list > div > div > div:nth-child(1) > div > mat-card > mat-card-content > div.subtitle > button > span > i')
  .wait('#mat-tab-content-0-0 > div > app-edit-bank-access-consent-component > div > div > button.right.mat-raised-button > span')
  .click('#mat-tab-content-0-0 > div > app-edit-bank-access-consent-component > div > div > button.right.mat-raised-button > span')
  .wait(2000)
  .click('#revokeBtn > span')
  .wait('#mat-tab-content-0-0 > div > app-connect-new-bank-component > div > div > div.bottomButtons > button > span')
  .end()
  .then(console.log)
  .catch(error => {
    console.error('Search failed:', error)
  })
